$axure.loadCurrentPage({
  "url":"dick_s.html",
  "generationDate":new Date(1393120601222.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStPage",
"AxStOrientation"],
  "page":{
    "packageId":"ee91cce768d54fde9ab92511a0570ab0",
    "type":"Axure:Page",
    "name":"Dick's",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4bfe88e131244fcd8e8f4ef3734aef56",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":29},
            "size":{
              "width":361,
              "height":471},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f3122ce0b51475a8eded2358ca5138a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":29},
                "size":{
                  "width":361,
                  "height":471},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u0.png"}},
{
          "id":"15212b40bb994447a4417ce72ad43928",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0066CC},
            "location":{
              "x":170,
              "y":499},
            "size":{
              "width":361,
              "height":74},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"051073f4211f435db59924be8089dc27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066CC},
                "location":{
                  "x":170,
                  "y":499},
                "size":{
                  "width":361,
                  "height":74},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u2.png"}},
{
          "id":"6ef03d1b006542ec90769c1e1733c683",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":511},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC00},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"694e8caab9584d68bbf2e9bf778cf129",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":511},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Main in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"main.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/restaurants_filter/u4.png"}},
{
          "id":"c03ffb4726464f94935d3739a5456c37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":511},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"2",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c733059139f4702a642d6997b6e7177",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":511},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"2",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Sightseeing Filter in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"sightseeing_filter.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/main/u4.png"}},
{
          "id":"21c2bb4aba1341a38156c5d398738981",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":511},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"2",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ff6210701be4c2c8c5d993453a96185",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":511},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"2",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Activities Filter in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"activities_filter.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/main/u4.png"}},
{
          "id":"ee3baa8561874b3ea95e2e71d7708705",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":511},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"2",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35cd8130d2ca423ab6e0f6ea8417e21a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":511},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"2",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Recreation Filter in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"recreation_filter.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/main/u4.png"}},
{
          "id":"4e2f4955fddb429bb2c15f2414418466",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":192,
              "y":519},
            "size":{
              "width":26,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75ce4d3f945e44a68dcf410044620b36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":192,
                  "y":519},
                "size":{
                  "width":26,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u12.png"}},
{
          "id":"8d7a37ca1ae24373bf0e621ac13fed51",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":257,
              "y":524},
            "size":{
              "width":35,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c531a61adfb64812bb40e37c8c12d95d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":257,
                  "y":524},
                "size":{
                  "width":35,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u14.png"}},
{
          "id":"09294cc7742f417d9a06d0ae1dae97f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":328,
              "y":521},
            "size":{
              "width":33,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4053f9419802467e8a74d6a4ff8d7542",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":328,
                  "y":521},
                "size":{
                  "width":33,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u16.png"}},
{
          "id":"8c5bd2b549a74697a0a794cedf967abc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":402,
              "y":524},
            "size":{
              "width":30,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6af60738f1604d9084003b9170259c3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":402,
                  "y":524},
                "size":{
                  "width":30,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dick_s/u18.png"}},
{
          "id":"ee0259dc4dc0464483fefebf44fe1526",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":507},
            "size":{
              "width":61,
              "height":56},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c3d68a28d4e4c29b0234b5f0629aa95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455,
                  "y":507},
                "size":{
                  "width":61,
                  "height":56},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u18.png"}},
{
          "id":"97cd27063b314cedbdf3df90a3e1c6a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":178,
              "y":38},
            "size":{
              "width":236,
              "height":29},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF888E96},
            "cornerRadiusTopLeft":"51.8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3c1a17ebe7c4a6896d5f009e7401b73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":178,
                  "y":38},
                "size":{
                  "width":236,
                  "height":29},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF888E96},
                "cornerRadiusTopLeft":"51.8"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"Open Search in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"search.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/main/u20.png"}},
{
          "id":"80a7bc7cdc2641c88de108028bd2434f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":184,
              "y":44},
            "size":{
              "width":17,
              "height":17},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec58173d5bb5416d956bea6c5d303850",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":184,
                  "y":44},
                "size":{
                  "width":17,
                  "height":17},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u22.png"}},
{
          "id":"85d2068d7906415db6b2f74116b5469a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFACACAC,
              "opacity":1},
            "location":{
              "x":209,
              "y":39},
            "size":{
              "width":123,
              "height":30},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edd73c7f1a664e8e92fd1887281081f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFACACAC,
                  "opacity":1},
                "location":{
                  "x":209,
                  "y":39},
                "size":{
                  "width":123,
                  "height":30},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"516dd7ad243343d2a30bc2bf971b91c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x5E0099FF},
            "location":{
              "x":305,
              "y":250},
            "size":{
              "width":80,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"890e80ae2b0946ddb4bb6851b1e814f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x5E0099FF},
                "location":{
                  "x":305,
                  "y":250},
                "size":{
                  "width":80,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u26.png"}},
{
          "id":"78f1dece6dc84b908863b9f703e71e78",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1B4EDC},
            "location":{
              "x":341,
              "y":286},
            "size":{
              "width":8,
              "height":8},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3965D5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b113464e4d7c48dd8648d7101ef59b1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1B4EDC},
                "location":{
                  "x":341,
                  "y":286},
                "size":{
                  "width":8,
                  "height":8},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3965D5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u28.png"}},
{
          "id":"ddecfab3c1f44b4985e46d2327f1b2ea",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "fill":{
              "fillType":"solid",
              "color":0xFF006600},
            "location":{
              "x":170,
              "y":168},
            "size":{
              "width":119,
              "height":122},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF003300},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0485fa716771482dafbf8d1ae3283993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006600},
                "location":{
                  "x":170,
                  "y":168},
                "size":{
                  "width":119,
                  "height":122},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF003300},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u30.png"}},
{
          "id":"2e95a67002d546ce8bc73e6ca2d86779",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":190},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"2",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54812cbf2c1f43fca3a02b8aff06ad56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":190},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"2",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u4.png"}},
{
          "id":"79ee73bb2f4b4ecfa4c953081db81b29",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":198},
            "size":{
              "width":26,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba14facbe2224b69ad6c420c8adba76d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":198},
                "size":{
                  "width":26,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u12.png"}},
{
          "id":"0513b7b4170647619db443b1f0461b85",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Scoder Hand Bold', 'Scoder Hand'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":172,
              "y":217},
            "size":{
              "width":145,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a02fafec9c74177bbf78efad72a5806",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Scoder Hand Bold', 'Scoder Hand'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":172,
                  "y":217},
                "size":{
                  "width":145,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd32f752a6894e808e28e11811cc4b65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":280,
              "y":211},
            "size":{
              "width":8,
              "height":9},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0731cec5db6b4b56853f8bbe7585d89d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":280,
                  "y":211},
                "size":{
                  "width":8,
                  "height":9},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dick_s/u40.png"}},
{
          "id":"f3bf11ef9fb44526a7e8ce4b6859c1c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF6C6F7B},
{
                  "color":0xFF6C6F7B},
{
                  "color":0xFF080A11},
{
                  "color":0xFF080A11}]},
            "location":{
              "x":302,
              "y":141},
            "size":{
              "width":218,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"28"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adfd9df6bfc2415b95bc8581e17d720d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF6C6F7B},
{
                      "color":0xFF6C6F7B},
{
                      "color":0xFF080A11},
{
                      "color":0xFF080A11}]},
                "location":{
                  "x":302,
                  "y":141},
                "size":{
                  "width":218,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"28"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dick_s/u42.png"}},
{
          "id":"dd753eb755064ad490259478c734e2b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF080D15},
{
                  "color":0xFF080D15},
{
                  "color":0xFF080A11},
{
                  "color":0xFF080A11}]},
            "location":{
              "x":302,
              "y":159},
            "size":{
              "width":218,
              "height":221},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"28"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ef24112f90e42b9be82ca39f82ec79d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF080D15},
{
                      "color":0xFF080D15},
{
                      "color":0xFF080A11},
{
                      "color":0xFF080A11}]},
                "location":{
                  "x":302,
                  "y":159},
                "size":{
                  "width":218,
                  "height":221},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"28"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dick_s/u44.png"}},
{
          "id":"9b67eb287dde492db69a6a8f434b3905",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFF080C14},
            "location":{
              "x":292,
              "y":207},
            "size":{
              "width":11,
              "height":19},
            "rotation":"180",
            "textRotation":"180",
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF080C14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27eac6dfceb64a85a8baeee0ef97599f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF080C14},
                "location":{
                  "x":292,
                  "y":207},
                "size":{
                  "width":11,
                  "height":19},
                "rotation":"180",
                "textRotation":"180",
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF080C14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dick_s/u46.png"}},
{
          "id":"d4c8982fd9d94d718d48291eda8bd3e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":348,
              "y":153},
            "size":{
              "width":132,
              "height":30},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26c828619d7c422795af5cfb3c3de72a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":348,
                  "y":153},
                "size":{
                  "width":132,
                  "height":30},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50c7fdb2668b4032beeb9145edd1ebeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFD2D2D7},
            "location":{
              "x":308,
              "y":179},
            "size":{
              "width":204,
              "height":191},
            "cornerRadiusTopLeft":"10.20001"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b140c16825e49ee8c1827e6a76c82fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD2D2D7},
                "location":{
                  "x":308,
                  "y":179},
                "size":{
                  "width":204,
                  "height":191},
                "cornerRadiusTopLeft":"10.20001"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dick_s/u50.png"}},
{
          "id":"a812ccf540524b0ea902ac0385cd4e66",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":316,
              "y":320},
            "size":{
              "width":84,
              "height":37},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"980f2dc26c134a759d2191baaf6ef13b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":316,
                  "y":320},
                "size":{
                  "width":84,
                  "height":37},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dick_s/u52.png"}},
{
          "id":"c9f727bc4f874fdfb42df6dda8f86b73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":424,
              "y":320},
            "size":{
              "width":83,
              "height":37},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eb2c0d7883f43559739fb3c6fbd3236",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":424,
                  "y":320},
                "size":{
                  "width":83,
                  "height":37},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dick_s/u54.png"}},
{
          "id":"eed93a4c34ef497fbd858efcdd31bc26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":187},
            "size":{
              "width":183,
              "height":122},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"533524612351411392f23f3d30fde853",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":187},
                "size":{
                  "width":183,
                  "height":122},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dick_s/u56.png"}},
{
          "id":"3841c4b910574244aab60b70a8b6b545",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":137},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"2",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49b4b2715f764466b1eaab37f97f1b37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":137},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"2",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u4.png"}},
{
          "id":"9f087746df4b4756a23f4a9dc83a381a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":482,
              "y":145},
            "size":{
              "width":26,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91cbe7492aa94e329152c3ec66ef2b6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":145},
                "size":{
                  "width":26,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u12.png"}},
{
          "id":"2d6f48a720574abb8daecef3e08c09ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":83},
            "size":{
              "width":53,
              "height":217}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9010cc13dc844b5e97d7c1f6a1dddb35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":83},
                "size":{
                  "width":53,
                  "height":217}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/main/u74.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4bfe88e131244fcd8e8f4ef3734aef56":{
      "scriptId":"u0"},
    "1f3122ce0b51475a8eded2358ca5138a":{
      "scriptId":"u1"},
    "15212b40bb994447a4417ce72ad43928":{
      "scriptId":"u2"},
    "051073f4211f435db59924be8089dc27":{
      "scriptId":"u3"},
    "6ef03d1b006542ec90769c1e1733c683":{
      "scriptId":"u4"},
    "694e8caab9584d68bbf2e9bf778cf129":{
      "scriptId":"u5"},
    "c03ffb4726464f94935d3739a5456c37":{
      "scriptId":"u6"},
    "2c733059139f4702a642d6997b6e7177":{
      "scriptId":"u7"},
    "21c2bb4aba1341a38156c5d398738981":{
      "scriptId":"u8"},
    "6ff6210701be4c2c8c5d993453a96185":{
      "scriptId":"u9"},
    "ee3baa8561874b3ea95e2e71d7708705":{
      "scriptId":"u10"},
    "35cd8130d2ca423ab6e0f6ea8417e21a":{
      "scriptId":"u11"},
    "4e2f4955fddb429bb2c15f2414418466":{
      "scriptId":"u12"},
    "75ce4d3f945e44a68dcf410044620b36":{
      "scriptId":"u13"},
    "8d7a37ca1ae24373bf0e621ac13fed51":{
      "scriptId":"u14"},
    "c531a61adfb64812bb40e37c8c12d95d":{
      "scriptId":"u15"},
    "09294cc7742f417d9a06d0ae1dae97f6":{
      "scriptId":"u16"},
    "4053f9419802467e8a74d6a4ff8d7542":{
      "scriptId":"u17"},
    "8c5bd2b549a74697a0a794cedf967abc":{
      "scriptId":"u18"},
    "6af60738f1604d9084003b9170259c3f":{
      "scriptId":"u19"},
    "ee0259dc4dc0464483fefebf44fe1526":{
      "scriptId":"u20"},
    "5c3d68a28d4e4c29b0234b5f0629aa95":{
      "scriptId":"u21"},
    "97cd27063b314cedbdf3df90a3e1c6a8":{
      "scriptId":"u22"},
    "e3c1a17ebe7c4a6896d5f009e7401b73":{
      "scriptId":"u23"},
    "80a7bc7cdc2641c88de108028bd2434f":{
      "scriptId":"u24"},
    "ec58173d5bb5416d956bea6c5d303850":{
      "scriptId":"u25"},
    "85d2068d7906415db6b2f74116b5469a":{
      "scriptId":"u26"},
    "edd73c7f1a664e8e92fd1887281081f5":{
      "scriptId":"u27"},
    "516dd7ad243343d2a30bc2bf971b91c0":{
      "scriptId":"u28"},
    "890e80ae2b0946ddb4bb6851b1e814f7":{
      "scriptId":"u29"},
    "78f1dece6dc84b908863b9f703e71e78":{
      "scriptId":"u30"},
    "b113464e4d7c48dd8648d7101ef59b1e":{
      "scriptId":"u31"},
    "ddecfab3c1f44b4985e46d2327f1b2ea":{
      "scriptId":"u32"},
    "0485fa716771482dafbf8d1ae3283993":{
      "scriptId":"u33"},
    "2e95a67002d546ce8bc73e6ca2d86779":{
      "scriptId":"u34"},
    "54812cbf2c1f43fca3a02b8aff06ad56":{
      "scriptId":"u35"},
    "79ee73bb2f4b4ecfa4c953081db81b29":{
      "scriptId":"u36"},
    "ba14facbe2224b69ad6c420c8adba76d":{
      "scriptId":"u37"},
    "0513b7b4170647619db443b1f0461b85":{
      "scriptId":"u38"},
    "3a02fafec9c74177bbf78efad72a5806":{
      "scriptId":"u39"},
    "bd32f752a6894e808e28e11811cc4b65":{
      "scriptId":"u40"},
    "0731cec5db6b4b56853f8bbe7585d89d":{
      "scriptId":"u41"},
    "f3bf11ef9fb44526a7e8ce4b6859c1c3":{
      "scriptId":"u42"},
    "adfd9df6bfc2415b95bc8581e17d720d":{
      "scriptId":"u43"},
    "dd753eb755064ad490259478c734e2b8":{
      "scriptId":"u44"},
    "0ef24112f90e42b9be82ca39f82ec79d":{
      "scriptId":"u45"},
    "9b67eb287dde492db69a6a8f434b3905":{
      "scriptId":"u46"},
    "27eac6dfceb64a85a8baeee0ef97599f":{
      "scriptId":"u47"},
    "d4c8982fd9d94d718d48291eda8bd3e2":{
      "scriptId":"u48"},
    "26c828619d7c422795af5cfb3c3de72a":{
      "scriptId":"u49"},
    "50c7fdb2668b4032beeb9145edd1ebeb":{
      "scriptId":"u50"},
    "0b140c16825e49ee8c1827e6a76c82fe":{
      "scriptId":"u51"},
    "a812ccf540524b0ea902ac0385cd4e66":{
      "scriptId":"u52"},
    "980f2dc26c134a759d2191baaf6ef13b":{
      "scriptId":"u53"},
    "c9f727bc4f874fdfb42df6dda8f86b73":{
      "scriptId":"u54"},
    "7eb2c0d7883f43559739fb3c6fbd3236":{
      "scriptId":"u55"},
    "eed93a4c34ef497fbd858efcdd31bc26":{
      "scriptId":"u56"},
    "533524612351411392f23f3d30fde853":{
      "scriptId":"u57"},
    "3841c4b910574244aab60b70a8b6b545":{
      "scriptId":"u58"},
    "49b4b2715f764466b1eaab37f97f1b37":{
      "scriptId":"u59"},
    "9f087746df4b4756a23f4a9dc83a381a":{
      "scriptId":"u60"},
    "91cbe7492aa94e329152c3ec66ef2b6e":{
      "scriptId":"u61"},
    "2d6f48a720574abb8daecef3e08c09ba":{
      "scriptId":"u62"},
    "9010cc13dc844b5e97d7c1f6a1dddb35":{
      "scriptId":"u63"}}});