$axure.loadCurrentPage({
  "url":"activities_filter.html",
  "generationDate":new Date(1393120601486.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStPage",
"AxStOrientation"],
  "page":{
    "packageId":"091f96079ab648a696e8c3cf03376c39",
    "type":"Axure:Page",
    "name":"Activities Filter",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c00a74ec677640ce84ec346e3f019235",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":29},
            "size":{
              "width":361,
              "height":471},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"613027186c0048c68af6bceebbb2f93c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":29},
                "size":{
                  "width":361,
                  "height":471},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u0.png"}},
{
          "id":"87285e4e6cb04620aebb2b11aa224219",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0066CC},
            "location":{
              "x":170,
              "y":499},
            "size":{
              "width":361,
              "height":74},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ab0aa782191465ba05ba8bdeba0563f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066CC},
                "location":{
                  "x":170,
                  "y":499},
                "size":{
                  "width":361,
                  "height":74},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u2.png"}},
{
          "id":"a1a3fe311f604472922cad2c243d9c6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":511},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"2",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de140825de294203b2a3d333a8f03a90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":511},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"2",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Restaurants Filter in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"restaurants_filter.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/main/u4.png"}},
{
          "id":"3448d23b6f7d4166b1bb750f36e87ee6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":511},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"2",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e87d7d105b084b6c863980fdd6d58de3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":511},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"2",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Sightseeing Filter in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"sightseeing_filter.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/main/u4.png"}},
{
          "id":"0c2284d781a043d5968ca99ca6a990fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":511},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC00},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d09252de83c04fceadab35a2312e7a5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":511},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Main in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"main.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/restaurants_filter/u4.png"}},
{
          "id":"4fc204f02d6b4649af1c1544d47cd723",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":511},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"2",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0a34f8890a04688b1f491abf309dae0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":511},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"2",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Recreation Filter in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"recreation_filter.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/main/u4.png"}},
{
          "id":"7386f10ada9e40d4ba4f684f9b438950",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":192,
              "y":519},
            "size":{
              "width":26,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33e6eebaf2ed4a148b70d3258a4ada17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":192,
                  "y":519},
                "size":{
                  "width":26,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u12.png"}},
{
          "id":"93998be28752404e9fc511d686307f9a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":257,
              "y":524},
            "size":{
              "width":35,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6b7cf025fa246aa93efcd833f9e0e4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":257,
                  "y":524},
                "size":{
                  "width":35,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u14.png"}},
{
          "id":"a471f3d1b0f0403a9a48dc20f2c2c88c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":328,
              "y":521},
            "size":{
              "width":33,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01395b019e6c4f32adb440c64d6ebe5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":328,
                  "y":521},
                "size":{
                  "width":33,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u16.png"}},
{
          "id":"09506092eb7044e2ad212323c85caf09",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":507},
            "size":{
              "width":61,
              "height":56},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f7f0ad815564e0c8d992a529e4dbb60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455,
                  "y":507},
                "size":{
                  "width":61,
                  "height":56},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u18.png"}},
{
          "id":"f179166c63b64f2ab7e903c10cab2520",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":178,
              "y":38},
            "size":{
              "width":236,
              "height":29},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF888E96},
            "cornerRadiusTopLeft":"51.8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"641cf293eb83439b9b75345143eaee2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":178,
                  "y":38},
                "size":{
                  "width":236,
                  "height":29},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF888E96},
                "cornerRadiusTopLeft":"51.8"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Search in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"search.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/main/u20.png"}},
{
          "id":"95cfcd1ba0f34ff2afc25697a6acd81d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":184,
              "y":44},
            "size":{
              "width":17,
              "height":17},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6604e68d9f7448a5b04a41af6f192245",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":184,
                  "y":44},
                "size":{
                  "width":17,
                  "height":17},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u22.png"}},
{
          "id":"61df56ce258d425dab74d4c0016c1189",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFACACAC,
              "opacity":1},
            "location":{
              "x":209,
              "y":39},
            "size":{
              "width":123,
              "height":30},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"750683dfce47452c98510f48262d018c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFACACAC,
                  "opacity":1},
                "location":{
                  "x":209,
                  "y":39},
                "size":{
                  "width":123,
                  "height":30},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa5acb31ce6f4518b6bf5eb474922e85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x5E0099FF},
            "location":{
              "x":305,
              "y":250},
            "size":{
              "width":80,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92daab416054465d9db45a16882f1ef0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x5E0099FF},
                "location":{
                  "x":305,
                  "y":250},
                "size":{
                  "width":80,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u26.png"}},
{
          "id":"9b00e917a65348b69ca91d201453c27a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1B4EDC},
            "location":{
              "x":341,
              "y":286},
            "size":{
              "width":8,
              "height":8},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3965D5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9b5e0f857b94877b4c646530d953c65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1B4EDC},
                "location":{
                  "x":341,
                  "y":286},
                "size":{
                  "width":8,
                  "height":8},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3965D5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u28.png"}},
{
          "id":"3bea48e12b864c898769b00df8ebd144",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "fill":{
              "fillType":"solid",
              "color":0xFF006600},
            "location":{
              "x":170,
              "y":168},
            "size":{
              "width":119,
              "height":122},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF003300},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57405d6cae764283aefddc9091277f86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006600},
                "location":{
                  "x":170,
                  "y":168},
                "size":{
                  "width":119,
                  "height":122},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF003300},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u30.png"}},
{
          "id":"2728cf595d1c4ff4abd367725a607307",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":209,
              "y":168},
            "size":{
              "width":9,
              "height":9},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dca3f35613640a7b301f893b1039980",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":209,
                  "y":168},
                "size":{
                  "width":9,
                  "height":9},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u32.png"}},
{
          "id":"542b8b8dee014427b6c4f44d0dce4a43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF6C6F7B},
{
                  "color":0xFF6C6F7B},
{
                  "color":0xFF080A11},
{
                  "color":0xFF080A11}]},
            "location":{
              "x":230,
              "y":157},
            "size":{
              "width":150,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"28"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6632419cbfc473bb02dba833bdb3650",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF6C6F7B},
{
                      "color":0xFF6C6F7B},
{
                      "color":0xFF080A11},
{
                      "color":0xFF080A11}]},
                "location":{
                  "x":230,
                  "y":157},
                "size":{
                  "width":150,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"28"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u34.png"}},
{
          "id":"ea3828670b484332898336df6c091a83",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF080D15},
{
                  "color":0xFF080D15},
{
                  "color":0xFF080A11},
{
                  "color":0xFF080A11}]},
            "location":{
              "x":230,
              "y":171},
            "size":{
              "width":150,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"28"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdc6438483e945ceb12d908a73c719c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF080D15},
{
                      "color":0xFF080D15},
{
                      "color":0xFF080A11},
{
                      "color":0xFF080A11}]},
                "location":{
                  "x":230,
                  "y":171},
                "size":{
                  "width":150,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"28"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u36.png"}},
{
          "id":"190bb8b275eb4392bfd80d0f597d9c7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFF080C14},
            "location":{
              "x":222,
              "y":164},
            "size":{
              "width":12,
              "height":19},
            "rotation":"180",
            "textRotation":"180",
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF080C14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fae3342c6833471aa4b35a2a364a33fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF080C14},
                "location":{
                  "x":222,
                  "y":164},
                "size":{
                  "width":12,
                  "height":19},
                "rotation":"180",
                "textRotation":"180",
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF080C14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u38.png"}},
{
          "id":"344731679fea41208344aabdb44b983a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":229,
              "y":166},
            "size":{
              "width":149,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84137641c6af48b280597384a6f30e55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":229,
                  "y":166},
                "size":{
                  "width":149,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65696a61e51e4ad6bdb6600e415a2988",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":148},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"2",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80035ac2e7f74c0796020c3a7630aee1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":351,
                  "y":148},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"2",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u4.png"}},
{
          "id":"f2fad2e0fa26414095c2fd89936504ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":359,
              "y":158},
            "size":{
              "width":33,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2dc2e55e5a14aa29fe1ed66545fb83d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":359,
                  "y":158},
                "size":{
                  "width":33,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u16.png"}},
{
          "id":"b25e55226ca14ab4b6fdd307e4f4221f",
          "label":"text",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Scoder Hand Bold', 'Scoder Hand'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":172,
              "y":217},
            "size":{
              "width":145,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02461ec1ffe44a47a7a74d74f6e81234",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Scoder Hand Bold', 'Scoder Hand'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":172,
                  "y":217},
                "size":{
                  "width":145,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bfa8fe0a7da49c69b5c310cf38054fb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":83},
            "size":{
              "width":53,
              "height":217}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f1e8f5f9c4f458ebe508822ea6e2cab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":83},
                "size":{
                  "width":53,
                  "height":217}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/main/u74.png"}},
{
          "id":"08e11131a23e40adb938b1f05b12c768",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":399.5,
              "y":520.5},
            "size":{
              "width":31,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ea51b717c0b47ae9f7c3692b243be87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":399.5,
                  "y":520.5},
                "size":{
                  "width":31,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u76.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c00a74ec677640ce84ec346e3f019235":{
      "scriptId":"u0"},
    "613027186c0048c68af6bceebbb2f93c":{
      "scriptId":"u1"},
    "87285e4e6cb04620aebb2b11aa224219":{
      "scriptId":"u2"},
    "7ab0aa782191465ba05ba8bdeba0563f":{
      "scriptId":"u3"},
    "a1a3fe311f604472922cad2c243d9c6b":{
      "scriptId":"u4"},
    "de140825de294203b2a3d333a8f03a90":{
      "scriptId":"u5"},
    "3448d23b6f7d4166b1bb750f36e87ee6":{
      "scriptId":"u6"},
    "e87d7d105b084b6c863980fdd6d58de3":{
      "scriptId":"u7"},
    "0c2284d781a043d5968ca99ca6a990fb":{
      "scriptId":"u8"},
    "d09252de83c04fceadab35a2312e7a5b":{
      "scriptId":"u9"},
    "4fc204f02d6b4649af1c1544d47cd723":{
      "scriptId":"u10"},
    "b0a34f8890a04688b1f491abf309dae0":{
      "scriptId":"u11"},
    "7386f10ada9e40d4ba4f684f9b438950":{
      "scriptId":"u12"},
    "33e6eebaf2ed4a148b70d3258a4ada17":{
      "scriptId":"u13"},
    "93998be28752404e9fc511d686307f9a":{
      "scriptId":"u14"},
    "d6b7cf025fa246aa93efcd833f9e0e4b":{
      "scriptId":"u15"},
    "a471f3d1b0f0403a9a48dc20f2c2c88c":{
      "scriptId":"u16"},
    "01395b019e6c4f32adb440c64d6ebe5f":{
      "scriptId":"u17"},
    "09506092eb7044e2ad212323c85caf09":{
      "scriptId":"u18"},
    "5f7f0ad815564e0c8d992a529e4dbb60":{
      "scriptId":"u19"},
    "f179166c63b64f2ab7e903c10cab2520":{
      "scriptId":"u20"},
    "641cf293eb83439b9b75345143eaee2a":{
      "scriptId":"u21"},
    "95cfcd1ba0f34ff2afc25697a6acd81d":{
      "scriptId":"u22"},
    "6604e68d9f7448a5b04a41af6f192245":{
      "scriptId":"u23"},
    "61df56ce258d425dab74d4c0016c1189":{
      "scriptId":"u24"},
    "750683dfce47452c98510f48262d018c":{
      "scriptId":"u25"},
    "aa5acb31ce6f4518b6bf5eb474922e85":{
      "scriptId":"u26"},
    "92daab416054465d9db45a16882f1ef0":{
      "scriptId":"u27"},
    "9b00e917a65348b69ca91d201453c27a":{
      "scriptId":"u28"},
    "c9b5e0f857b94877b4c646530d953c65":{
      "scriptId":"u29"},
    "3bea48e12b864c898769b00df8ebd144":{
      "scriptId":"u30"},
    "57405d6cae764283aefddc9091277f86":{
      "scriptId":"u31"},
    "2728cf595d1c4ff4abd367725a607307":{
      "scriptId":"u32"},
    "9dca3f35613640a7b301f893b1039980":{
      "scriptId":"u33"},
    "542b8b8dee014427b6c4f44d0dce4a43":{
      "scriptId":"u34"},
    "a6632419cbfc473bb02dba833bdb3650":{
      "scriptId":"u35"},
    "ea3828670b484332898336df6c091a83":{
      "scriptId":"u36"},
    "bdc6438483e945ceb12d908a73c719c0":{
      "scriptId":"u37"},
    "190bb8b275eb4392bfd80d0f597d9c7e":{
      "scriptId":"u38"},
    "fae3342c6833471aa4b35a2a364a33fa":{
      "scriptId":"u39"},
    "344731679fea41208344aabdb44b983a":{
      "scriptId":"u40"},
    "84137641c6af48b280597384a6f30e55":{
      "scriptId":"u41"},
    "65696a61e51e4ad6bdb6600e415a2988":{
      "scriptId":"u42"},
    "80035ac2e7f74c0796020c3a7630aee1":{
      "scriptId":"u43"},
    "f2fad2e0fa26414095c2fd89936504ec":{
      "scriptId":"u44"},
    "b2dc2e55e5a14aa29fe1ed66545fb83d":{
      "scriptId":"u45"},
    "b25e55226ca14ab4b6fdd307e4f4221f":{
      "scriptId":"u46"},
    "02461ec1ffe44a47a7a74d74f6e81234":{
      "scriptId":"u47"},
    "4bfa8fe0a7da49c69b5c310cf38054fb":{
      "scriptId":"u48"},
    "6f1e8f5f9c4f458ebe508822ea6e2cab":{
      "scriptId":"u49"},
    "08e11131a23e40adb938b1f05b12c768":{
      "scriptId":"u50"},
    "3ea51b717c0b47ae9f7c3692b243be87":{
      "scriptId":"u51"}}});